foreground              #fcedee
background              #695150
selection_foreground    #6b5a5f
selection_background    #d9aeb5
cursor                  #f5d8c8
cursor_text_color       #fcedee

active_tab_foreground     #fcedee
active_tab_background     #fff7f8
inactive_tab_foreground   #fff7f8
inactive_tab_background   #fcedee

# Pink 1
color0      #fcedee
color8      #e8c9cc

# Pink 2
color1      #e8c9cc
color9      #e3bcc2

# Pink 3
color2      #e3bcc2
color10     #d9aeb5

# Cream 1
color3      #fdede3
color11     #f8dfd1

# Cream 2
color4      #f8dfd1
color12     #f5d8c8

# Cream 3
color5      #f5d8c8
color13     #c2a38f

# Brown 1
color6      #8a747a
color14     #6b5a5f

# Brown 2
color7      #6b5a5f
color15     #8a747a
